//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Dados.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;
	using Client.Zeus.Dados;
	using Client.Zeus.Dados.Base;
	using Client.Zeus.Domain;

	public partial class MenuRepository : GenericRepository<TB_MENU>
	{
		public MenuRepository(Contexto contexto)
			: base(contexto)
		{
		}
	}
}
