//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Domain
{
    using System;
    using System.Collections.Generic;
    
    							   
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;	 
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Client.Zeus.Domain.Base;
    using Client.Zeus.Util.Attributes;
    
    [MetadataType(typeof(TB_FUNCIONALIDADEMetaData))]
    [DataContract]
    public partial class TB_FUNCIONALIDADE : BaseDomain
    {
        public TB_FUNCIONALIDADE()
        {
            this.TB_PERFIL = new HashSet<TB_PERFIL>();
        }
    
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string DESCRICAO { get; set; }
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string CONTROLLER { get; set; }
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string ACTION { get; set; }
    	[DataMember]
        public Nullable<int> ID_MENU { get; set; }
    
    	[DataMember]
        public virtual TB_MENU TB_MENU { get; set; }
    	[DataMember]
        public virtual ICollection<TB_PERFIL> TB_PERFIL { get; set; }
    }
    
    /// <summary>
    /// Classe opcional para configurar alguma validação não padrão.
    /// </summary>
    public partial class TB_FUNCIONALIDADEMetaData 
    {
    }
}
