//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHS.ProjetoBaseMvc.Dominio
{
    using System;
    using System.Collections.Generic;
    
    							   
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;	 
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using BHS.ProjetoBaseMvc.Dominio.Base;
    using BHS.ProjetoBaseMvc.Util.Attributes;
    
    [MetadataType(typeof(TB_PERFILMetaData))]
    [DataContract]
    public partial class TB_PERFIL : DominioBase
    {
        public TB_PERFIL()
        {
            this.TB_FUNCIONALIDADE = new HashSet<TB_FUNCIONALIDADE>();
            this.TB_MENU = new HashSet<TB_MENU>();
            this.TB_USUARIO = new HashSet<TB_USUARIO>();
        }
    
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string DESCRICAO { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public bool ADMIN { get; set; }
    
    	[DataMember]
        public virtual ICollection<TB_FUNCIONALIDADE> TB_FUNCIONALIDADE { get; set; }
    	[DataMember]
        public virtual ICollection<TB_MENU> TB_MENU { get; set; }
    	[DataMember]
        public virtual ICollection<TB_USUARIO> TB_USUARIO { get; set; }
    }
    
    /// <summary>
    /// Classe opcional para configurar alguma validação não padrão.
    /// </summary>
    public partial class TB_PERFILMetaData 
    {
    }
}
