//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Business.Gerenciador
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Text;
	using System.Threading.Tasks;
	using Client.Zeus.Data;
	using Client.Zeus.Data.Repository;
	using Client.Zeus.Domain;	 
	using Client.Zeus.Domain.PesquisaDTO;
	using Client.Zeus.Business.Base;

	public partial class CidadeGerenciador : BaseManager<TB_CIDADE>
	{
		public CidadeGerenciador()
			: base()
		{
		}

		public CidadeGerenciador(Contexto contexto)
			: base(contexto)
		{
		}

		public CidadeGerenciador(Adapter adaptador)
			: base(adaptador)
		{
		}		  

		public CidadeRepositorio Repositorio
		{
			get
			{
				return (CidadeRepositorio)base.BaseRepository;
			}
		}
	}
}
