//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Zeus.Util.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atualizado com sucesso..
        /// </summary>
        public static string AtualizadoComSucesso {
            get {
                return ResourceManager.GetString("AtualizadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do CEP deve ser informado com 8 dígitos..
        /// </summary>
        public static string CepInvalido {
            get {
                return ResourceManager.GetString("CepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP informado não encontrou endereço válido..
        /// </summary>
        public static string CepNaoEncontrado {
            get {
                return ResourceManager.GetString("CepNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta atividade está em conflito de dia e horário com outro em seu calendário..
        /// </summary>
        public static string ConflitoAtividade {
            get {
                return ResourceManager.GetString("ConflitoAtividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} criado com sucesso..
        /// </summary>
        public static string CriadoComSucesso {
            get {
                return ResourceManager.GetString("CriadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir o {0} {1} ? Esta operação não poderá ser revertida..
        /// </summary>
        public static string DesejaExcluir {
            get {
                return ResourceManager.GetString("DesejaExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alterado com sucesso..
        /// </summary>
        public static string EditadaComSucesso {
            get {
                return ResourceManager.GetString("EditadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo do campo e-mail deve ser composto por, no mínimo: nomeUsuario@provedor.com..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja enviar e-mail para todos os contatos selecionados? Esta ação não poderá ser revertida..
        /// </summary>
        public static string EnviarEmail {
            get {
                return ResourceManager.GetString("EnviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível gerar o relatório a partir dos dados informados..
        /// </summary>
        public static string ErroGerarRelatorio {
            get {
                return ResourceManager.GetString("ErroGerarRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} excluído com sucesso..
        /// </summary>
        public static string ExcluidoComSucesso {
            get {
                return ResourceManager.GetString("ExcluidoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuncionarioInativo..
        /// </summary>
        public static string FuncionarioInativo {
            get {
                return ResourceManager.GetString("FuncionarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta atividade já possui o número máximo de inscritos..
        /// </summary>
        public static string LimiteInscritosAtividade {
            get {
                return ResourceManager.GetString("LimiteInscritosAtividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login informado não existe..
        /// </summary>
        public static string LoginInexistente {
            get {
                return ResourceManager.GetString("LoginInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou senha incorretos..
        /// </summary>
        public static string LoginSenhaIncorretos {
            get {
                return ResourceManager.GetString("LoginSenhaIncorretos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns campos obrigatórios não foram preenchidos..
        /// </summary>
        public static string ModelStateInvalido {
            get {
                return ResourceManager.GetString("ModelStateInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado para os dados informados..
        /// </summary>
        public static string NenhumRegistro {
            get {
                return ResourceManager.GetString("NenhumRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        public static string OperacaoRealizadaComSucesso {
            get {
                return ResourceManager.GetString("OperacaoRealizadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect já existe. Os dados serão disponibilizados para atualização..
        /// </summary>
        public static string ProspectExistente {
            get {
                return ResourceManager.GetString("ProspectExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja resolver os Follow Ups selecionados?.
        /// </summary>
        public static string ResolverFollowUps {
            get {
                return ResourceManager.GetString("ResolverFollowUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas digitadas não conferem..
        /// </summary>
        public static string SenhaAtualNaoConfere {
            get {
                return ResourceManager.GetString("SenhaAtualNaoConfere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os valuees inseridos nos campos Senha e Confirmação de Senha não são iguais..
        /// </summary>
        public static string SenhaDiferenteConfirmacaoDeSenha {
            get {
                return ResourceManager.GetString("SenhaDiferenteConfirmacaoDeSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual incorreta..
        /// </summary>
        public static string SenhaIncorreta {
            get {
                return ResourceManager.GetString("SenhaIncorreta", resourceCulture);
            }
        }
    }
}
