//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Data.Repository
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;
	using Client.Zeus.Data;
	using Client.Zeus.Data.Base;
	using Client.Zeus.Domain;

	public partial class FuncionalidadeRepository : GenericRepository<TB_FUNCIONALIDADE>
	{
		public FuncionalidadeRepository(Contexto contexto)
			: base(contexto)
		{
		}
	}
}
