//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHS.ProjetoBaseMvc.App.CrudService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoListaTotalOfTB_CIDADE_Suar5u8q", Namespace="http://schemas.datacontract.org/2004/07/BHS.ProjetoBaseMvc.Contrato.Entidade")]
    [System.SerializableAttribute()]
    public partial class RetornoListaTotalOfTB_CIDADE_Suar5u8q : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE> ListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalItensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE> Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItens {
            get {
                return this.TotalItensField;
            }
            set {
                if ((this.TotalItensField.Equals(value) != true)) {
                    this.TotalItensField = value;
                    this.RaisePropertyChanged("TotalItens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoComMensagem", Namespace="http://schemas.datacontract.org/2004/07/BHS.ProjetoBaseMvc.Contrato.Entidade")]
    [System.SerializableAttribute()]
    public partial class RetornoComMensagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ErrosValidacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ErrosValidacao {
            get {
                return this.ErrosValidacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrosValidacaoField, value) != true)) {
                    this.ErrosValidacaoField = value;
                    this.RaisePropertyChanged("ErrosValidacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((this.RetornoField.Equals(value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoListaTotalOfTB_UF_Suar5u8q", Namespace="http://schemas.datacontract.org/2004/07/BHS.ProjetoBaseMvc.Contrato.Entidade")]
    [System.SerializableAttribute()]
    public partial class RetornoListaTotalOfTB_UF_Suar5u8q : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_UF> ListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalItensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_UF> Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItens {
            get {
                return this.TotalItensField;
            }
            set {
                if ((this.TotalItensField.Equals(value) != true)) {
                    this.TotalItensField = value;
                    this.RaisePropertyChanged("TotalItens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrudService.ICrudContrato")]
    public interface ICrudContrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarCidade", ReplyAction="http://tempuri.org/ICrudContrato/ListarCidadeResponse")]
        System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE> ListarCidade();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarCidade", ReplyAction="http://tempuri.org/ICrudContrato/ListarCidadeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE>> ListarCidadeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarPaginadoCidade", ReplyAction="http://tempuri.org/ICrudContrato/ListarPaginadoCidadeResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_CIDADE_Suar5u8q ListarPaginadoCidade(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarPaginadoCidade", ReplyAction="http://tempuri.org/ICrudContrato/ListarPaginadoCidadeResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_CIDADE_Suar5u8q> ListarPaginadoCidadeAsync(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/BuscarPorIdCidade", ReplyAction="http://tempuri.org/ICrudContrato/BuscarPorIdCidadeResponse")]
        BHS.ProjetoBaseMvc.Dominio.TB_CIDADE BuscarPorIdCidade(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/BuscarPorIdCidade", ReplyAction="http://tempuri.org/ICrudContrato/BuscarPorIdCidadeResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE> BuscarPorIdCidadeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/CriarCidade", ReplyAction="http://tempuri.org/ICrudContrato/CriarCidadeResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem CriarCidade(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoNovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/CriarCidade", ReplyAction="http://tempuri.org/ICrudContrato/CriarCidadeResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> CriarCidadeAsync(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoNovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/EditarCidade", ReplyAction="http://tempuri.org/ICrudContrato/EditarCidadeResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem EditarCidade(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoEditado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/EditarCidade", ReplyAction="http://tempuri.org/ICrudContrato/EditarCidadeResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> EditarCidadeAsync(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoEditado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirCidade", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirCidadeResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirCidade(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirCidade", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirCidadeResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirCidadeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirVariosCidade", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirVariosCidadeResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirVariosCidade(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirVariosCidade", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirVariosCidadeResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirVariosCidadeAsync(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarUF", ReplyAction="http://tempuri.org/ICrudContrato/ListarUFResponse")]
        System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_UF> ListarUF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarUF", ReplyAction="http://tempuri.org/ICrudContrato/ListarUFResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_UF>> ListarUFAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarPaginadoUF", ReplyAction="http://tempuri.org/ICrudContrato/ListarPaginadoUFResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_UF_Suar5u8q ListarPaginadoUF(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ListarPaginadoUF", ReplyAction="http://tempuri.org/ICrudContrato/ListarPaginadoUFResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_UF_Suar5u8q> ListarPaginadoUFAsync(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/BuscarPorIdUF", ReplyAction="http://tempuri.org/ICrudContrato/BuscarPorIdUFResponse")]
        BHS.ProjetoBaseMvc.Dominio.TB_UF BuscarPorIdUF(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/BuscarPorIdUF", ReplyAction="http://tempuri.org/ICrudContrato/BuscarPorIdUFResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.Dominio.TB_UF> BuscarPorIdUFAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/CriarUF", ReplyAction="http://tempuri.org/ICrudContrato/CriarUFResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem CriarUF(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoNovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/CriarUF", ReplyAction="http://tempuri.org/ICrudContrato/CriarUFResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> CriarUFAsync(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoNovo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/EditarUF", ReplyAction="http://tempuri.org/ICrudContrato/EditarUFResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem EditarUF(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoEditado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/EditarUF", ReplyAction="http://tempuri.org/ICrudContrato/EditarUFResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> EditarUFAsync(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoEditado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirUF", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirUFResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirUF(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirUF", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirUFResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirUFAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirVariosUF", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirVariosUFResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirVariosUF(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/ExcluirVariosUF", ReplyAction="http://tempuri.org/ICrudContrato/ExcluirVariosUFResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirVariosUFAsync(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/TestarServico", ReplyAction="http://tempuri.org/ICrudContrato/TestarServicoResponse")]
        BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem TestarServico(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudContrato/TestarServico", ReplyAction="http://tempuri.org/ICrudContrato/TestarServicoResponse")]
        System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> TestarServicoAsync(System.Collections.Generic.List<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrudContratoChannel : BHS.ProjetoBaseMvc.App.CrudService.ICrudContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudContratoClient : System.ServiceModel.ClientBase<BHS.ProjetoBaseMvc.App.CrudService.ICrudContrato>, BHS.ProjetoBaseMvc.App.CrudService.ICrudContrato {
        
        public CrudContratoClient() {
        }
        
        public CrudContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE> ListarCidade() {
            return base.Channel.ListarCidade();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE>> ListarCidadeAsync() {
            return base.Channel.ListarCidadeAsync();
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_CIDADE_Suar5u8q ListarPaginadoCidade(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina) {
            return base.Channel.ListarPaginadoCidade(paginaAtual, ordenacao, direcaoOrdenacao, quantidadePorPagina);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_CIDADE_Suar5u8q> ListarPaginadoCidadeAsync(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina) {
            return base.Channel.ListarPaginadoCidadeAsync(paginaAtual, ordenacao, direcaoOrdenacao, quantidadePorPagina);
        }
        
        public BHS.ProjetoBaseMvc.Dominio.TB_CIDADE BuscarPorIdCidade(int id) {
            return base.Channel.BuscarPorIdCidade(id);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.Dominio.TB_CIDADE> BuscarPorIdCidadeAsync(int id) {
            return base.Channel.BuscarPorIdCidadeAsync(id);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem CriarCidade(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoNovo) {
            return base.Channel.CriarCidade(objetoNovo);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> CriarCidadeAsync(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoNovo) {
            return base.Channel.CriarCidadeAsync(objetoNovo);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem EditarCidade(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoEditado) {
            return base.Channel.EditarCidade(objetoEditado);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> EditarCidadeAsync(BHS.ProjetoBaseMvc.Dominio.TB_CIDADE objetoEditado) {
            return base.Channel.EditarCidadeAsync(objetoEditado);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirCidade(int id) {
            return base.Channel.ExcluirCidade(id);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirCidadeAsync(int id) {
            return base.Channel.ExcluirCidadeAsync(id);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirVariosCidade(System.Collections.Generic.List<int> id) {
            return base.Channel.ExcluirVariosCidade(id);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirVariosCidadeAsync(System.Collections.Generic.List<int> id) {
            return base.Channel.ExcluirVariosCidadeAsync(id);
        }
        
        public System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_UF> ListarUF() {
            return base.Channel.ListarUF();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BHS.ProjetoBaseMvc.Dominio.TB_UF>> ListarUFAsync() {
            return base.Channel.ListarUFAsync();
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_UF_Suar5u8q ListarPaginadoUF(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina) {
            return base.Channel.ListarPaginadoUF(paginaAtual, ordenacao, direcaoOrdenacao, quantidadePorPagina);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoListaTotalOfTB_UF_Suar5u8q> ListarPaginadoUFAsync(int paginaAtual, string ordenacao, string direcaoOrdenacao, int quantidadePorPagina) {
            return base.Channel.ListarPaginadoUFAsync(paginaAtual, ordenacao, direcaoOrdenacao, quantidadePorPagina);
        }
        
        public BHS.ProjetoBaseMvc.Dominio.TB_UF BuscarPorIdUF(int id) {
            return base.Channel.BuscarPorIdUF(id);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.Dominio.TB_UF> BuscarPorIdUFAsync(int id) {
            return base.Channel.BuscarPorIdUFAsync(id);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem CriarUF(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoNovo) {
            return base.Channel.CriarUF(objetoNovo);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> CriarUFAsync(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoNovo) {
            return base.Channel.CriarUFAsync(objetoNovo);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem EditarUF(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoEditado) {
            return base.Channel.EditarUF(objetoEditado);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> EditarUFAsync(BHS.ProjetoBaseMvc.Dominio.TB_UF objetoEditado) {
            return base.Channel.EditarUFAsync(objetoEditado);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirUF(int id) {
            return base.Channel.ExcluirUF(id);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirUFAsync(int id) {
            return base.Channel.ExcluirUFAsync(id);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem ExcluirVariosUF(System.Collections.Generic.List<int> id) {
            return base.Channel.ExcluirVariosUF(id);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> ExcluirVariosUFAsync(System.Collections.Generic.List<int> id) {
            return base.Channel.ExcluirVariosUFAsync(id);
        }
        
        public BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem TestarServico(System.Collections.Generic.List<int> id) {
            return base.Channel.TestarServico(id);
        }
        
        public System.Threading.Tasks.Task<BHS.ProjetoBaseMvc.App.CrudService.RetornoComMensagem> TestarServicoAsync(System.Collections.Generic.List<int> id) {
            return base.Channel.TestarServicoAsync(id);
        }
    }
}
