//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MENU()
        {
            this.TB_FUNCTIONALITY = new HashSet<TB_FUNCTIONALITY>();
            this.TB_MENU1 = new HashSet<TB_MENU>();
            this.TB_PERFIL = new HashSet<TB_PERFIL>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public string IMAGE { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public string URL { get; set; }
        public bool FLAG_NEW_PAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FUNCTIONALITY> TB_FUNCTIONALITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MENU> TB_MENU1 { get; set; }
        public virtual TB_MENU TB_MENU2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PERFIL> TB_PERFIL { get; set; }
    }
}
