//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHS.ProjetoBaseMvc.Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using BHS.ProjetoBaseMvc.Dominio;
    
    public partial class Contexto : DbContext
    {
        public Contexto()
            : base("name=Contexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_UF> TB_UF { get; set; }
        public DbSet<TB_CIDADE> TB_CIDADE { get; set; }
        public DbSet<TB_USUARIO> TB_USUARIO { get; set; }
        public DbSet<TB_MENU> TB_MENU { get; set; }
        public DbSet<TB_PERFIL> TB_PERFIL { get; set; }
        public DbSet<TB_PERFIL_MENU> TB_PERFIL_MENU { get; set; }
        public DbSet<TB_PERFIL_USUARIO> TB_PERFIL_USUARIO { get; set; }
        public DbSet<TB_FUNCIONALIDADE> TB_FUNCIONALIDADE { get; set; }
        public DbSet<TB_PERFIL_FUNCIONALIDADE> TB_PERFIL_FUNCIONALIDADE { get; set; }
    }
}
