//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Domain
{
    using System;
    using System.Collections.Generic;
    
    							   
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;	 
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Client.Zeus.Domain.Base;
    using Client.Zeus.Util.Attributes;
    
    [MetadataType(typeof(TB_MENUMetaData))]
    [DataContract]
    public partial class TB_MENU : BaseDomain
    {
        public TB_MENU()
        {
            this.TB_FUNCTIONALITY = new HashSet<TB_FUNCTIONALITY>();
            this.TB_MENU1 = new HashSet<TB_MENU>();
            this.TB_PERFIL = new HashSet<TB_PERFIL>();
        }
    
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string TITLE { get; set; }
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
    	[DataMember]
        public string CONTROLLER { get; set; }
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
    	[DataMember]
        public string ACTION { get; set; }
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
    	[DataMember]
        public string IMAGE { get; set; }
    	[DataMember]
        public Nullable<int> ID_PARENT { get; set; }
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
    	[DataMember]
        public string URL { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public bool FLAG_NEW_PAGE { get; set; }
    
    	[DataMember]
        public virtual ICollection<TB_FUNCTIONALITY> TB_FUNCTIONALITY { get; set; }
    	[DataMember]
        public virtual ICollection<TB_MENU> TB_MENU1 { get; set; }
    	[DataMember]
        public virtual TB_MENU TB_MENU2 { get; set; }
    	[DataMember]
        public virtual ICollection<TB_PERFIL> TB_PERFIL { get; set; }
    }
    
    /// <summary>
    /// Classe opcional para configurar alguma validação não padrão.
    /// </summary>
    public partial class TB_MENUMetaData 
    {
    }
}
