//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Domain
{
    using System;
    using System.Collections.Generic;
    
    							   
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;	 
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Client.Zeus.Domain.Base;
    using Client.Zeus.Util.Attributes;
    
    [MetadataType(typeof(TB_PERFILMetaData))]
    [DataContract]
    public partial class TB_PERFIL : BaseDomain
    {
        public TB_PERFIL()
        {
            this.TB_FUNCTIONALITY = new HashSet<TB_FUNCTIONALITY>();
            this.TB_MENU = new HashSet<TB_MENU>();
            this.TB_USER = new HashSet<TB_USER>();
        }
    
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public bool ADMIN { get; set; }
    
    	[DataMember]
        public virtual ICollection<TB_FUNCTIONALITY> TB_FUNCTIONALITY { get; set; }
    	[DataMember]
        public virtual ICollection<TB_MENU> TB_MENU { get; set; }
    	[DataMember]
        public virtual ICollection<TB_USER> TB_USER { get; set; }
    }
    
    /// <summary>
    /// Classe opcional para configurar alguma validação não padrão.
    /// </summary>
    public partial class TB_PERFILMetaData 
    {
    }
}
