//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Zeus.Domain
{
    using System;
    using System.Collections.Generic;
    
    							   
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;	 
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Client.Zeus.Domain.Base;
    using Client.Zeus.Util.Attributes;
    
    [MetadataType(typeof(TB_USERMetaData))]
    [DataContract]
    public partial class TB_USER : BaseDomain
    {
        public TB_USER()
        {
            this.TB_PERFIL = new HashSet<TB_PERFIL>();
        }
    
        
        [StringLength(50, ErrorMessage="Este campo não pode ser maior que 50 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string NAME { get; set; }
        
        [StringLength(256, ErrorMessage="Este campo não pode ser maior que 256 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string PASSWORD { get; set; }
        
        [EmailAddress(ErrorMessage = "E-mail inválido")]
        
        [StringLength(128, ErrorMessage="Este campo não pode ser maior que 128 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string EMAIL { get; set; }
        
        [StringLength(20, ErrorMessage="Este campo não pode ser maior que 20 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
    	[DataMember]
        public string LOGIN { get; set; }
    
    	[DataMember]
        public virtual ICollection<TB_PERFIL> TB_PERFIL { get; set; }
    }
    
    /// <summary>
    /// Classe opcional para configurar alguma validação não padrão.
    /// </summary>
    public partial class TB_USERMetaData 
    {
    }
}
