//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHS.ProjetoBaseMvc.Dados.Repositorio
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;
	using BHS.ProjetoBaseMvc.Dados;
	using BHS.ProjetoBaseMvc.Dados.Base;
	using BHS.ProjetoBaseMvc.Dominio;

	public partial class UsuarioRepositorio : RepositorioGenerico<TB_USUARIO>
	{
		public UsuarioRepositorio(Contexto contexto)
			: base(contexto)
		{
		}
	}
}
